// JobRadar AI — Reporter Agent
// -------------------------------------------------------------
// อ่าน ranked-jobs.csv (ผลจาก Matcher) → สร้าง "digest" สวย ๆ
//   • digest.md   — สำหรับโพสต์/อ่าน/ส่ง LINE-Discord
//   • digest.html — email-ready (เอาไปยิงเข้า Gmail ได้เลย)
// ไม่ต้องใช้ API key — เป็นขั้น "Transform + Store" ล้วน ๆ
//
// รัน:  node report.mjs   (หรือ npm run report)
// -------------------------------------------------------------
import { readFileSync, writeFileSync } from "node:fs";

// ---- ตั้งค่า ----
const IN = "ranked-jobs.csv";
const TOP_N = 10;
const FIT_THRESHOLD = 70; // fit >= เท่านี้ ถือว่า "น่าสมัคร"

// parser CSV เดียวกับ match.mjs (ไว้ค่อยแยกเป็น lib ตอนทำ orchestrator)
function parseCsv(text) {
  text = text.replace(/^﻿/, "");
  const rows = [];
  let row = [], field = "", q = false;
  for (let i = 0; i < text.length; i++) {
    const c = text[i];
    if (q) {
      if (c === '"') { if (text[i + 1] === '"') { field += '"'; i++; } else q = false; }
      else field += c;
    } else if (c === '"') q = true;
    else if (c === ",") { row.push(field); field = ""; }
    else if (c === "\n") { row.push(field); rows.push(row); row = []; field = ""; }
    else if (c !== "\r") field += c;
  }
  if (field.length || row.length) { row.push(field); rows.push(row); }
  return rows;
}

// ---- 1) อ่านงานที่จัดอันดับแล้ว ----
const rows = parseCsv(readFileSync(IN, "utf8"));
const header = rows[0];
const jobs = rows.slice(1)
  .filter((r) => r.length >= header.length && r.some(Boolean))
  .map((r) => Object.fromEntries(header.map((h, i) => [h, r[i] ?? ""])));

// ---- 2) คำนวณ metric (% ที่เอาไปโชว์ในพอร์ต) ----
const total = jobs.length;
const scores = jobs.map((j) => Number(j.score) || 0);
const avg = Math.round(scores.reduce((a, b) => a + b, 0) / (total || 1));
const strong = jobs.filter((j) => Number(j.score) >= FIT_THRESHOLD).length;
const top = jobs.slice(0, TOP_N); // Matcher เรียงมาให้แล้ว (มาก→น้อย)
const today = new Date().toISOString().slice(0, 10);

// ---- 3) สร้าง Markdown digest ----
const md = `# 🎯 JobRadar AI — Daily Digest · ${today}

> สแกน **${total}** ประกาศงาน · fit เฉลี่ย **${avg}%** · น่าสมัคร (fit ≥ ${FIT_THRESHOLD}): **${strong}** งาน

## 🏆 Top ${top.length}

${top.map((j, i) =>
  `**${i + 1}. [${j.position}](${j.url})** — \`${j.score}/100\` · ${j.company}\n` +
  `   ↳ ${j.reason}`
).join("\n\n")}

---
*Generated by JobRadar AI — ranked ${total} jobs, showing top ${top.length}.*
`;
writeFileSync("digest.md", md, "utf8");

// ---- 4) สร้าง HTML digest (email-ready, inline CSS) ----
const scoreColor = (s) => (s >= 70 ? "#16a34a" : s >= 45 ? "#d97706" : "#9ca3af");
const cards = top.map((j, i) => `
    <tr><td style="padding:14px 0;border-bottom:1px solid #eee;">
      <table width="100%"><tr>
        <td style="font:700 15px system-ui;color:#111;">
          ${i + 1}. <a href="${j.url}" style="color:#111;text-decoration:none;">${j.position}</a>
          <span style="color:#888;font-weight:400;"> · ${j.company}</span>
        </td>
        <td align="right" style="white-space:nowrap;">
          <span style="background:${scoreColor(j.score)};color:#fff;font:700 12px system-ui;padding:3px 9px;border-radius:999px;">${j.score}/100</span>
        </td>
      </tr></table>
      <div style="font:400 13px system-ui;color:#666;margin-top:4px;">↳ ${j.reason}</div>
    </td></tr>`).join("");

const html = `<!doctype html><html><body style="margin:0;background:#f6f6f6;">
  <table width="100%" cellpadding="0" cellspacing="0"><tr><td align="center" style="padding:24px;">
    <table width="600" cellpadding="0" cellspacing="0" style="background:#fff;border-radius:14px;overflow:hidden;">
      <tr><td style="background:#111;padding:24px 28px;">
        <div style="font:800 20px system-ui;color:#fff;">🎯 JobRadar <span style="color:#ef4444;">AI</span></div>
        <div style="font:400 13px system-ui;color:#aaa;margin-top:2px;">Daily Digest · ${today}</div>
      </td></tr>
      <tr><td style="padding:18px 28px;background:#fafafa;border-bottom:1px solid #eee;font:600 13px system-ui;color:#444;">
        สแกน ${total} งาน &nbsp;·&nbsp; fit เฉลี่ย <b>${avg}%</b> &nbsp;·&nbsp; น่าสมัคร (≥${FIT_THRESHOLD}): <b style="color:#16a34a;">${strong}</b> งาน
      </td></tr>
      <tr><td style="padding:8px 28px 22px;"><table width="100%">${cards}</table></td></tr>
      <tr><td style="padding:16px 28px;background:#111;font:400 12px system-ui;color:#888;">Generated by JobRadar AI</td></tr>
    </table>
  </td></tr></table>
</body></html>`;
writeFileSync("digest.html", html, "utf8");

// ---- 5) สรุปบนหน้าจอ ----
console.log(`📊 JobRadar Digest · ${today}`);
console.log(`   สแกน ${total} งาน · fit เฉลี่ย ${avg}% · น่าสมัคร(≥${FIT_THRESHOLD}): ${strong} งาน`);
console.log(`\n   Top ${Math.min(3, top.length)} ตัวอย่าง:`);
for (const j of top.slice(0, 3)) console.log(`   ${String(j.score).padStart(3)} · ${j.position} @ ${j.company}`);
console.log(`\n✅ เขียนแล้ว: digest.md + digest.html`);
